### ISSUE TITLE
设计模式--单例篇   Error: Missing initializer in const declaration

### ISSUE THREAD

**Issue by objcxiaobai** [MuYunyun/blog#104]
> 文章有描述错误的地方欢迎指正交流。

error:
```
const getSingle = function(fn) {
  const result
  return function() {
    return result || result = fn.apply(this, arguments)
  }
};
```

update:
```
const getSingle = function(fn) {
  var result;
  return function() {
    if(result){
     return result 
    }
    return result = fn.apply(this, arguments)
  }
};
```

**Comment by MuYunyun** [comment]
@objcxiaobai Thanks, I've corrected it, and welcome your pr.

```diff
const getSingle = function(fn) {
-  const result
+  let result
  return function() {
    return result || result = fn.apply(this, arguments)
  }
}
```

**Comment by objcxiaobai** [comment]
> @objcxiaobai Thanks, I've corrected it, and welcome your pr.
> 
> ```diff
> const getSingle = function(fn) {
> -  const result
> +  let result
>   return function() {
>     return result || result = fn.apply(this, arguments)
>   }
> }
> ```

but, the  code `return result || result = fn.apply(this, arguments)`  Uncaught SyntaxError: Invalid left-hand side in assignment

**Comment by MuYunyun** [comment]
@objcxiaobai  I'm sorry to forget the operator precedence 😄 

```diff
const getSingle = function(fn) {
-  const result
+  let result
  return function() {
-    return result || result = fn.apply(this, arguments)
+   return result || (result = fn.apply(this, arguments))
  }
}
```
