### ISSUE TITLE
http://muyunyun.cn/blog/ 404了

### ISSUE THREAD

**Issue by foreverwang** [MuYunyun/blog#115]
> 文章有描述错误的地方欢迎指正交流。

http://muyunyun.cn/blog/ 404了

**Comment by MuYunyun** [comment]
> > 文章有描述错误的地方欢迎指正交流。
> 
> http://muyunyun.cn/blog/ 404了

感谢反馈, 晚点我排查下

**Comment by MuYunyun** [comment]
本地目前定位到报错: `[prerender-spa-plugin] Unable to prerender all routes! [Error: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded]`

![image](https://user-images.githubusercontent.com/19354791/119075190-f959d300-ba22-11eb-8797-b757b8355519.png)

相关 issue
* https://github.com/chrisvfritz/prerender-spa-plugin/issues/242

**Comment by MuYunyun** [comment]
@foreverwang 已修复。

**Comment by pompeyY** [comment]
http://muyunyun.cn/blog/ 又404啦
