### ISSUE TITLE
React Conf 2021

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/blog#147]
### Link

* [React Conf 2021](https://www.youtube.com/watch?v=8dUpL8SCO1w)

### Topic

* [React 18 for App Developers](https://youtu.be/8dUpL8SCO1w?t=2935) 0:48
  * introduce how to modify React from 16 to 18.
* [Streaming Server Rendering with Suspense](https://youtu.be/8dUpL8SCO1w?t=4084) 1:08
* [The First React Working Group](https://youtu.be/8dUpL8SCO1w?t=5203) 1:26
  * UseSyncExternalStore
  * UseId: 后续待探究，是否使用该 hooks 可以避免组件多一次 render 的问题。
  * UseInsertionEffect: for helping CSS-IN-JS libraries.
* [React Developer Tooling](https://youtu.be/8dUpL8SCO1w?t=6086) 1:41
* [React Without Memo](https://youtu.be/8dUpL8SCO1w?t=6855) 1:54
  * React Forget
* [React Docs Keynote](https://youtu.be/8dUpL8SCO1w?t=8116) 2:15
* [Things I Learnt from the New React Docs](https://youtu.be/8dUpL8SCO1w?t=8722) 2:25
* [Learning in the Browser——zero to React in One Window](https://youtu.be/8dUpL8SCO1w?t=9281) 2:34
* [The ROI OF Designing With React](https://youtu.be/8dUpL8SCO1w?t=9925) 2:45
* [Interactive Playgrounds with React](https://youtu.be/8dUpL8SCO1w?t=10592) 2:56
* [Re-introducing Relay](https://youtu.be/8dUpL8SCO1w?t=11722) 3:15
* [React Native Desktop](https://youtu.be/8dUpL8SCO1w?t=12892) 3:34
* [On-device Machine Learning for React Native](https://youtu.be/8dUpL8SCO1w?t=13825) 3:50
* [React 18 for External Store Libraries](https://youtu.be/8dUpL8SCO1w?t=15323) 4:15
  * 【Todo: do search in useSyncExternalStore】useSyncExternalStore
* [Building Accessible Components with React 18](https://youtu.be/8dUpL8SCO1w?t=16486) 4:34
* [Accessible Japanese Form Components with React](https://youtu.be/8dUpL8SCO1w?t=16996) 4:43
* [UI Tools for Artists](https://youtu.be/8dUpL8SCO1w?t=17630) 4:53
* [Hydrogen + React 18](https://youtu.be/8dUpL8SCO1w?t=18245) 5:04

**Comment by fecrh** [comment]
你好，你发的邮件我已收到，谢谢
