### ISSUE TITLE
1.JSX 和 Virtual DOM

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/blog#24]
该系列文章在实现 cpreact 的同时理顺 React 框架的核心内容

> [项目地址](https://github.com/MuYunyun/cpreact)

### 环境准备

首先安装以下 babel 模块，其具体作用会在后文 [JSX 和 虚拟 DOM](https://github.com/MuYunyun/blog/blob/master/从0到1实现React/1.JSX和虚拟DOM.md) 中提及

> 扩展延伸：[babel 执行机制](https://github.com/MuYunyun/blog/blob/master/BasicSkill/番外篇/babel执行机制.md)

```js
"@babel/core": "^7.0.0",
"@babel/preset-env": "^7.0.0",
"@babel/preset-react": "^7.0.0",
"babel-loader": "v8.0.0-beta.0",
```

同时 `.babelrc` 配置如下：

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "> 0.25%, not dead",
        "useBuiltIns": "entry"
      }
    ],
    [
      "@babel/preset-react",
      {
        "pragma": "cpreact.createElement" // 该参数传向 transform-react-jsx 插件，是前置的一个核心，后文有解释为什么使用 cpreact.createElement
      }
    ]
  ]
}
```

配置好 babel 后，接着提供两套打包工具的配置方案，读者可以自行选择。

#### 方案 1：使用 webpack

webpack 拥有一个活跃的社区，提供了更为丰富的打包能力。

首先安装以下模块：

```
"webpack": "^4.17.2",
"webpack-cli": "^3.1.0",
"webpack-dev-server": "^3.1.8"
```

在根目录的 `webpack.config.js` 配置如下：

```js
const webpack = require('webpack')
const path = require('path')
const rootPath = path.resolve(__dirname)

module.exports = {
  entry: path.resolve(rootPath, 'test', 'index.js'),
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist'
  },
  output: {
    filename: 'cpreact.js',
    path: path.resolve(rootPath, 'dist'),
    libraryTarget: 'umd'
  },
  module: {
    rules: [{
      test: /\.js$/,
      loader: "babel-loader",
    }]
  },
}
```

然后在 `package.json` 里加上如下配置：

```
"scripts": {
  "start": "webpack-dev-server --open",
},
```

具体可以参照 [0.4.3 版本](https://github.com/MuYunyun/cpreact/blob/master/webpack.config.js)

#### 方案 2：使用 parcel

[parcel](https://parceljs.org/getting_started.html) 是一款上手极快的打包工具，使用其可以快速地进入项目开发的状态。在 `package.json` 加上如下配置，具体可以参照 [0.1 版本](https://github.com/MuYunyun/cpreact/blob/0.1/package.json)

```
"scripts": {
  "start": "parcel ./index.html --open -p 8080 --no-cache"
},
```

### JSX 和 虚拟 DOM

```js
const element = (
  <div className="title">
    hello<span className="content">world!</span>
  </div>
)
```

JSX 是一种语法糖，经过 [babel](https://babeljs.io/en/repl) 转换结果如下，可以发现实际上转化成 `React.createElement()` 的形式：

> 扩展：[babel执行机制](https://github.com/MuYunyun/blog/blob/master/BasicSkill/番外篇/babel执行机制.md)

```js
var element = React.createElement(
  "div",
  { className: "title" },
  "hello",
  React.createElement(
    "span",
    { className: "content" },
    "world!"
  )
);
```

[打印](https://preactjs.com/repl) element, 结果如下：

```js
{
  attributes: {className: "title"}
  children: ["hello", t] // t 和外层对象相同
  key: undefined
  nodeName: "div"
}
```

因此，我们得出结论：JSX 语法糖经过 Babel 编译后转换成一种对象，该对象即所谓的`虚拟 DOM`，使用虚拟 DOM 能让页面进行更为高效的渲染。

我们按照这种思路进行函数的构造：

```js
const React = {
  createElement
}

function createElement(tag, attr, ...child) {
  return {
    attributes: attr,
    children: child,
    key: undefined,
    nodeName: tag,
  }
}

// 测试
const element = (
  <div className="title">
    hello<span className="content">world!</span>
  </div>
)

console.log(element) // 打印结果符合预期
// {
//   attributes: {className: "title"}
//   children: ["hello", t] // t 和外层对象相同
//   key: undefined
//   nodeName: "div"
// }
```

### 虚拟 DOM 转化为真实 DOM

上个小节介绍了 JSX 转化为虚拟 DOM 的过程，这个小节接着来实现将虚拟 DOM 转化为真实 DOM (页面上渲染的是真实 DOM)。

我们知道在 React 中，将虚拟 DOM 转化为真实 DOM 是使用 `ReactDOM.render` 实现的，使用如下：

```js
import ReactDOM from 'react-dom'

ReactDOM.render(
  element, // 上文的 element，即虚拟 dom
  document.getElementById('root')
)
```

接着来实现 `ReactDOM.render` 的逻辑:

```js
const ReactDOM = {
  render
}

/**
 * 将虚拟 DOM 转化为真实 DOM
 * @param {*} vdom      虚拟 DOM
 * @param {*} container 需要插入的位置
 */
function render(vdom, container) {
  if (typeof(vdom) === 'string') {
    container.innerText = vdom
    return
  }
  const dom = document.createElement(vdom.nodeName)
  for (let attr in vdom.attributes) {
    setAttribute(dom, attr, vdom.attributes[attr])
  }
  vdom.children.forEach(vdomChild => render(vdomChild, dom))
  container.appendChild(dom)
}

/**
 * 给节点设置属性
 * @param {*} dom   操作元素
 * @param {*} attr  操作元素属性
 * @param {*} value 操作元素值
 */
function setAttribute(dom, attr, value) {
  if (attr === 'className') {
    attr = 'class'
  }
  if (attr.match(/on\w+/)) {   // 处理事件的属性:
    const eventName = attr.toLowerCase().splice(1)
    dom.addEventListener(eventName, value)
  } else if (attr === 'style') { // 处理样式的属性:
    let styleStr = ''
    let standardCss
    for (let klass in value) {
      standardCss = humpToStandard(klass) // 处理驼峰样式为标准样式
      value[klass] = _.isNumber(+value[klass]) ? value[klass] + 'px' : value[klass] // style={{ className: '20' || '20px' }}>
      styleStr += `${standardCss}: ${value[klass]};`
    }
    dom.setAttribute(attr, styleStr)
  } else {                       // 其它属性
    dom.setAttribute(attr, value)
  }
}
```

至此，我们成功将虚拟 DOM 复原为真实 DOM，展示如下：

![](http://oqhtscus0.bkt.clouddn.com/a898514bd3d08df4366e5ceb7843cddf.jpg-400)

另外配合热更新，在热更新的时候清空之前的 dom 元素，改动如下：

```js
const ReactDOM = {
  render(vdom, container) {
    container.innerHTML = null
    render(vdom, container)
  }
}
```

### 总结

`JSX` 经过 babel 编译为 React.createElement() 的形式，其返回结果就是 `Virtual DOM`，最后通过 ReactDOM.render() 将 Virtual DOM 转化为真实的 DOM 展现在界面上。流程图如下：

![](http://oqhtscus0.bkt.clouddn.com/5e451855ccc9017708b57164f9e221c6.jpg-400)

### 思考题

如下是一个 react/preact 的常用组件的写法，那么为什么要 import 一个 React 或者 h 呢？

```jsx
import React, { Component } from 'react' // react
// import { h, Component } from 'preact' // preact

class A extends Component {
  render() {
    return <div>I'm componentA</div>
  }
}

render(<A />, document.body) // 组件的挂载
```

### 项目说明

该系列文章会尽可能的分析项目细节，具体的还是以项目实际代码为准。

### 鸣谢
Especially thank [simple-react](https://github.com/hujiulong/simple-react) for the guidance function of this library. At the meantime，respect for [preact](https://github.com/developit/preact) and [react](https://github.com/facebook/react)

**Comment by limengke123** [comment]
讲的挺好的，感谢！
所以，为什么要 import 一个 React 或者 h 呢？

**Comment by MuYunyun** [comment]
@limengke123 拿 React 来说，JSX 经过 babel 编译为 React.createElement() 的形式，所以要引人 React，从而调用其 createElement 方法生成 Virtual DOM。

**Comment by hujiulong** [comment]
你这照着我的文章写https://github.com/hujiulong/blog/issues/4 就自己改了几个字？又不写引用

**Comment by MuYunyun** [comment]
@hujiulong 确实拜读了您的文章，在后文中我提到了借鉴了您的库的，我补充下。另外我是看了您的源码后自己从头实现的，有些细节部分也有自己的思考在里面。再次感谢您的文章给我的启发。

**Comment by hujiulong** [comment]
@MuYunyun 从你现在的几篇相关文章来看，不仅仅是借鉴我库的实现吧。就说现在这篇文章，使用的打包工具，文章的组织，各小结内容，代码，包括最后的问题，都和我的文章基本一样，这种重复程度不是在后面一篇文章中提一句simple-react就能撇清关系吧。我的博客仓库写了[分享协议](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)，任何共享和**演绎**只要注明作者并给出链接就行了，这点要求都做不到吗。
我的文章能给你启发，并且想继续扩展，这我很赞成，这也是我写技术文章的目的之一，但是希望你做的这些建立在尊重原作者成果的前提下。

**Comment by MuYunyun** [comment]
@hujiulong 恩，之前确实疏忽了分享协议了，之后的演绎会注意 :tada:

**Comment by hujiulong** [comment]
行了我删了，以后注意一点

**Comment by MuYunyun** [comment]
@hujiulong 大佬的系列文章真的是写得很赞，填补了市面上相关资料的空缺，希望日后能跟紧大佬的步伐，我也会继续深耕下去，日后望大佬多加点拨，再次向您学习 👍，感谢

**Comment by Y-wson** [comment]
你写的文章很好，通俗易懂，谢谢作者的分享

**Comment by MuYunyun** [comment]
@Y-wson 可以动手实现一遍，收获会很大。

**Comment by Y-wson** [comment]
@MuYunyun 
那段代码应该改成
if (attr.match(/on\w+/)) {   // 处理事件的属性:
		const eventName = attr.toLowerCase().substring(2);
		dom.addEventListener(eventName, value)
这样子吧，splice会报错的

**Comment by Y-wson** [comment]
@MuYunyun 
文章中的代码有错误，和code里面的不一样

**Comment by MuYunyun** [comment]
@Y-wson 这篇文章的 code 可以参考 [第一版的实现](https://github.com/MuYunyun/cpreact/blob/0.1/src/index.js)

**Comment by MuYunyun** [comment]
如果是学习用的话，在文章后面注明引用，我蛮欢迎的。另外如果对代码部分有什么好的见解可以交流:smile:

**Comment by Y-wson** [comment]
好的，我也是才学习源码，觉得你的文章通俗易懂，多向你学习

**Comment by MuYunyun** [comment]
@Y-wson 互相学习，这个系列等下会更新一篇文章，等下发布 :tada:

**Comment by MuYunyun** [comment]
@ppq1991 目前也计划着跑 [测试用例](https://github.com/MuYunyun/cpreact/tree/master/test)，至于你反馈的这个点我感觉应该不是 bug，你可以在 [测试文件](https://github.com/MuYunyun/cpreact/blob/master/test/index.js) 中跑下设想的场景，看看是否与预期不符。使用方法：

```js
npm install -g parcel-bundler

npm run start
```

**Comment by ppq1991** [comment]
@MuYunyun 你的测试文件 VDOM 结构太简单了，没有覆盖多个 `children` 的场景。

```html
<div>
  child - 1
  <span>child - 2</span>
  child - only show this
</div>
```

如果不用 `TextNode`，遇到 `String` 你就直接 `innerText = 'xxx'` 了，之前的 `children` 都被清空了。

**Comment by MuYunyun** [comment]
@ppq1991 我明白你的意思了，在后面的章节中是有解决这个问题的，比如第二章中采用如下的方式来优化：

```js
  if (_.isString(vdom) || _.isNumber(vdom)) {
    container.innerText = container.innerText + vdom
    return
  }
```

以及再后面章节更为优化的代码，这是一个循序渐进的过程。

```js
  if (_.isString(vdom) || _.isNumber(vdom)) {
    const textNode = document.createTextNode(vdom)
    return textNode
  }
```

因为这是一个从 0 到 1 实现 react 的过程，很多细节不能构思得一步到位，都是循序渐进的。后面的章节中在增加新特性的时候也会补充前面遗留的坑。感谢持续跟进与交流。

**Comment by Y-wson** [comment]
你这里面有个小错误，setAttribute里面匹配事件的正则不应该加引号

**Comment by MuYunyun** [comment]
@Y-wson 已更正
