### ISSUE TITLE
拼多多内推(长期有效)

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/blog#35]
### 社招

拼多多 - 商户前端团队(其它团队也可以帮推)
- 团队大佬: 大 boss 为 dubbo 框架作者 https://github.com/apache/dubbo
- 与自己关系：所在业务线招人, 目前有大量 hc
- 岗位名称：
  - 资深前端工程师、前端架构师/技术专家
- 薪资带宽：很多~无上限
- 工作城市：上海金虹桥
- 工作内容：拼多多商家平台 PC、移动、小程序、Node 服务等多端技术的系统研发工作
- 内推人：我
- 联系方式：发送简历到 myy0320@qq.com 或者加微信联系 a328375795

### 职能介绍

<details>
  <summary>资深前端工程师</summary>

### 职能介绍

* 负责拼多多商家平台涉及 PC 、移动、小程序、Node 服务等多端技术的系统研发工作；
* 团队注重商家用户体验的提升，对前端体验与性能优化做到极致，对代码、设计与交互有洁癖和一定追求；
* 技术栈涉及整个前端体系，包括微前端框架、移动端组件包、自研服务端渲染框架；
* 技术资产包括但不限于 UI 组件库、脚手架、构建工具、数据可视化、通用模块等基础设施的建设；
* 用打造产品的思维，从业务、设计、架构层面思考如何拆解，更高的复用，更有效的实现；
* 具备产品工程师思维，注重积累与技术创新，与团队一起打造技术产品，提升行业技术影响力；

### 岗位要求

* 本科及以上学历，计算机专业领域基础扎实，2年以上Web开发经验；
* 熟练使用 ECMA-262 及以上版本及 TypeScript 语言进行开发；
* 掌握常用 IDE 配置，常规 Lint 类工具及类型检查、持续集成工具的使用；
* 熟练使用业界常用 JavaScript 库或框架（React 为主 / Vue / Angular），熟练掌握 Hooks 的使用；
* 熟悉 HTTP 规范，对 HTTP/2、GraphQL、REST 有自己的理解；
* 熟悉常用单元测试、集成测试框架的基本使用；
* 熟悉前端工程化解决方案（Webpack / Rollup.js）的使用和基本原理；
* 具备一定的代码洁癖与良好的技术总结能力；

### 加分项

* 对服务端渲染技术（SSR）、服务端技术（Node.js）、微前端框架有开发经验加分；
* 熟悉电商领域业务经验加分；
* 对线上系统异常监控、巡检、自动化测试有涉猎加分；
* 有大规模前端项目、UI 组件开发、复杂交互、复杂状态系统的开发经验加分；
* 从事过服务端、客户端、用户体验设计，具备相应技能加分；
* 熟练使用函数式编程风格或面向对象编程风格开发加分；
* 对前端领域技术（如：响应式编程、微前端架构、Schema AST 等）有深入理解加分；
* 具备数据可视化，可视化构建系统建设，浏览器插件开发经验加分；

</details>

<details>
  <summary>前端架构师/技术专家</summary>

### 职能介绍

* 负责拼多多商家平台涉及 PC 、移动、小程序、Node 服务等多端技术的系统研发工作；
* 团队注重商家用户体验的提升，对前端体验与性能优化做到极致，对代码、设计与交互有洁癖和一定追求；
* 技术栈涉及整个前端体系，包括微前端框架、移动端组件包、自研服务端渲染框架；
* 技术资产包括但不限于 UI 组件库、脚手架、构建工具、数据可视化、通用模块等基础设施的建设；
* 优化前端团队的开发方式和流程、规范，提高团队效率；
* 用打造产品的思维，从业务、设计、架构层面思考如何拆解，更高的复用，更有效的实现；
* 具备产品工程师思维，注重积累与技术创新，与团队一起打造技术产品，提升行业技术影响力；

### 岗位要求

* 本科及以上学历，计算机专业领域基础扎实，2年以上Web开发经验，掌握常用数据结构与算法；
* 熟练使用 ECMA-262 及以上版本及 TypeScript 语言进行开发，熟悉模块化加载机制；
* 掌握常用 IDE 配置，常规 Lint 类工具及类型检查、持续集成工具的使用及二次开发；
* 熟练使用业界常用 JavaScript 库或框架（React 为主 / Vue / Angular），熟练掌握 Hooks 的使用；
* 熟悉 HTTP 规范，对 HTTP/2、GraphQL、REST 有自己的理解与使用经验；
* 熟悉常用单元测试、集成测试框架的基本使用，并能进行二次封装；
* 熟练掌握 CSS 样式工具库的使用，具备优秀的样式封装与复用能力；
* 掌握集成测试、线上部署、性能监控及调优等技术方案；
* 熟悉前端工程化解决方案（Webpack / Rollup.js）的使用和基本原理，了解 Loader / Plugin 的原理及实现；
* 具备一定的代码洁癖与良好的技术总结能力；
* 具备良好的性能调优与 Web 网络安全意识；

### 加分项

* 对服务端渲染技术（SSR）、服务端技术（Node.js）、微前端框架有开发经验加分；
* 熟悉电商领域业务经验加分；
* 有大规模前端项目、UI 组件开发、复杂交互、复杂状态系统的开发经验加分；
* 对线上系统异常监控、巡检、自动化测试有涉猎加分；
* 从事过服务端、客户端、用户体验设计，具备相应技能加分；
* 熟练使用函数式编程风格或面向对象编程风格开发加分；
* 对前端领域技术（如：响应式编程、微前端架构、Schema AST 等）有深入理解加分；
* 参与效率工程相关技术，具备数据可视化，可视化构建，浏览器插件开发经验加分；

</details>

**Comment by snakeUni** [comment]
Awesome!   send your resume to `lanyincao@pinduoduo.com`

**Comment by luckyoneday** [comment]
感兴趣的可以将简历发送至`youting@pinduoduo.com`

**Comment by zbl1996** [comment]
后端转前端可以吗

**Comment by MuYunyun** [comment]
@zbl1996 可以的, 我同事就是后端转岗前端的 :smile:

**Comment by pingan8787** [comment]
优秀优秀
